export const COMMENTSTRING =
  `
/* eslint-disable */
/* tslint:disable */
// THIS FILE IS AUTOGENERATED AND MANAGED BY BARRELBOT. DO NOT EDIT`;

export type FILETYPE = 'js' | 'jsx' | 'ts' | 'tsx';
export const INDEXEXTENSIONS = ['js', 'ts', 'jsx', 'tsx'];
export const INDEXFILES = INDEXEXTENSIONS.map(x => 'index.' + x);
export type NAMESPACETYPE = 'none' | 'all' | 'defaultOnly';
